FROM alpine:3

RUN apk update && \
    apk add git && \
    git clone https://github.com/attiliodrei/souin.git /plugins-local/src/github.com/attiliodrei/souin \
      --depth 1 --single-branch --branch v1.6.14

FROM traefik:v2.7.3
COPY --from=0 /plugins-local /plugins-local
COPY --from=0 /plugins-local/src/github.com/attiliodrei/souin/plugins/traefik/traefik.toml /traefik.toml
COPY --from=0 /plugins-local/src/github.com/attiliodrei/souin/plugins/traefik/souin-configuration.yaml /souin-configuration.yaml

CMD ["--experimental.localPlugins.souin.moduleName=github.com/attiliodrei/souin"]

